### ISSUE TITLE
感谢叶老师推荐《现代统计图形》

### ISSUE THREAD

**Issue by XiangyunHuang** [fyemath/fyemath.github.io#1]
叶老师：

您好！感谢您为《现代统计图形》写推荐语，人民邮电出版社通知我们书籍即将出版，为表达感谢，赠送您一本书。谢益辉让我收集您的**国内**收件地址和联系方式，以便出版社投递，如您方便，烦请告知，再次感谢！

收件地址和联系方式烦请发送至邮箱 xiangyunfaith@outlook.com

**Comment by fyemath** [comment]
> 叶老师：
> 
> 您好！感谢您为《现代统计图形》写推荐语，人民邮电出版社通知我们书籍即将出版，为表达感谢，赠送您一本书。谢益辉让我收集您的**国内**收件地址和联系方式，以便出版社投递，如您方便，烦请告知，再次感谢！
> 
> 收件地址和联系方式烦请发送至邮箱 [xiangyunfaith@outlook.com](mailto:xiangyunfaith@outlook.com)

黄老师：
你好！非常感谢！已经给你发了邮件了。请查收。

祝好！

**Comment by XiangyunHuang** [comment]
已经收到了，我把issues关闭了
